administrative-area:
  - address: "taizhou"
    name: "泰州市"
    children:
      - { address: "suqian", name: "经济开发区" }
      - { address: "economic", name: "经济开发区" }
      - { address: "hailing", name: "海陵区" }
      - { address: "gaogang", name: "高港区" }
      - { address: "jiangyan", name: "姜堰区" }
      - { address: "xinghua", name: "兴化市" }
      - { address: "jingjiang", name: "靖江市" }
      - { address: "taixing", name: "泰兴市" }

disguise-headers:
  Referer: "https://onetalk.alibaba.com/"
  Sec-Ch-Ua: '"Chromium";v="128", "Not;A=Brand";v="24", "Microsoft Edge";v="128"'
  Sec-Ch-Ua-Mobile: "?0"
  Sec-Ch-Ua-Platform: '"Windows"'
  User-Agent: "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/128.0.0.0 Safari/537.36 Edg/128.0.0.0"
  Cookie: "ali_apache_id=33.102.195.127.1726301220921.401634.5; cna=JTJsH/uvk2UCAXAEsdIbziUK; t=cbd56c20b81c1fdd2657c81f71fb4f99; xman_us_f=x_l=1; xlly_s=1; _m_h5_tk=3ce5eb1823346cfed6da63befcc835f1_1726640160335; _m_h5_tk_enc=c2252cc739556f62cef3f571ecf9e48d; xman_f=rzJPZe36A5rJIT8lnaCRb2fBfbzWR0NV2D8v+g9QWTxShv+U4fuBSBpj/E8td1lWYCvPx2u7XvAEVGqqQIrcrQKx45G3lVEHGhnLHbeD38NiK99J09VTmw==; ali_apache_track=; cookie2=18c712df9daf1c37e3d8aa3f390b8472; icbu_s_tag=9_11; ali_apache_tracktmp=; isg=BP7-BHfQFEPUXEBonDFH6zvxTxRAP8K50XUYv6gH08E8S54lEM_HySy5wReH87rR; acs_usuc_t=acs_rt=600f3d3f97894b02bde4b47160c3767e; xman_t=fHvO27WWAiN9ls0ZfoE81h0VT++N74KKHCiLlZPCV6mZrHj3TOfygPJ+q8ydkhRT; c_csrf=47682994-7b95-4ced-a8fe-5ac9543f2444; _samesite_flag_=true; _tb_token_=399ede61f5bb; NWG=SNW; JSESSIONID=1D5F9E1ACFD942EBDB836B32D87606EF; ug_se_c=organic_1726632005509; tfstk=fJWqxwD2F-eV87wsCnJwYt5vcd9v_K4IsOT6jGjMcEYc5C9ZIMQJ5od65_kNzUZvCsN9QC76PtTfcKYN7asgDCGbHGAGrwsXCoIibhb5rNRTDFTM7NsGGuwQdiIvBdbaRJwBvzk8RN-DsI2ujHKmsav8vpsvBd4SMazlhiQElFCAIdqyEh-IsdxmiQqyfH-DIEAirbxHrdYGSCmorH-mIqDDjQqyXUxDIdcDvijiUHO0AiQ3YeDMEI8h4WHZIekBieYHrA4hUnWM-iYrIAYx6tRf4iaqpg9ALw-Cl8DV8GjdsQWZry8OUgXcsg34qpSPN6OVarDwPtTW9tvEj-jy3ERhEInqHwjPj6OPFk2p3KYc1KIsYrsP3ZsAUGiiZKJfaBW2KJ3D5_sFQhWTW87FjMCMaOuV4r09qIbCBsui_IxJ4eZz461VAQJCnYet6fdkp38QcnGt6IxB4eZrcfh9MvKyRoCf."

captcha-detect:
  landmarks: ["_config_", "captcha", "punish"]

json-parser:
  landmark: "_PAGE_DATA_"
  prefix: "window._PAGE_DATA_ = {"
  suffix: "};"
  offer-list-path: ["offerResultData", "offerList"]
  offer-template:
    detail-url: "action"
    name: "companyName"
    provided-products: "provideProducts"

xpath:
  bill:
    - '//*[@id="8919138051"]/div/div/div/div[3]/div/table/tr[3]/td[2]/div/div/div'
    - '//*[@id="8945312245"]/div/div[2]/div[1]/ul/li[3]/strong'
  address:
    - '//*[@id="8919138051"]/div/div/div/div[3]/div/table/tr[1]/td[4]/div/div/div'
