administrative-area:
  - address: "taizhou"
    name: "泰州市"
    children:
      - { address: "jingjiang", name: "靖江市" }
      - { address: "taixing", name: "泰兴市" }
      - { address: "xinghua", name: "兴化市" }
      - { address: "hailing", name: "海陵区" }
      - { address: "gaogang", name: "高港区" }
      - { address: "jiangyan", name: "姜堰区" }

chrome-driver:
  path: "D:/ProgramData/WebDrivers/Chrome/129.0.6668.58/chromedriver.exe"
  options:
    - "log-level=3"
    - "--incognito"
    - "--no-sandbox"
    - "--disable-dev-shm-usage"
    - "--disable-blink-features=AutomationControlled"
  experimental-options:
    "useAutomationExtension": false
    "excludeSwitches": ["enable-automation"]
    prefs: { "profile.default_content_setting_values": { "images": 2 } }
  cdp-command:
    "Page.addScriptToEvaluateOnNewDocument":
      "source": >
        Object.defineProperty(navigator, 'webdriver', {
          get: () => undefined
        })

json-parser:
  landmark: "_PAGE_DATA_"
  prefix: "window._PAGE_DATA_ = {"
  suffix: "};"
  offer-list-path: ["offerResultData", "offerList"]
  offer-template:
    detail-url: "action"
    name: "companyName"
    provided-products: "provideProducts"

xpath:
  bill:
    - '//*[@id="8919138051"]/div/div/div/div[3]/div/table/tr[3]/td[2]/div/div/div'
    - '//*[@id="8945312245"]/div/div[2]/div[1]/ul/li[3]/strong'
  address:
    - '//*[@id="8919138051"]/div/div/div/div[3]/div/table/tr[1]/td[4]/div/div/div'
  orders:
    - '//*[@id="8945312245"]/div/div[2]/div[1]/ul/li[3]/div'
