administrative-area:
  - address: "taizhou"
    name: "泰州市"
    children:
      - { address: "suqian", name: "经济开发区" }
      - { address: "economic", name: "经济开发区" }
      - { address: "hailing", name: "海陵区" }
      - { address: "gaogang", name: "高港区" }
      - { address: "jiangyan", name: "姜堰区" }
      - { address: "xinghua", name: "兴化市" }
      - { address: "jingjiang", name: "靖江市" }
      - { address: "taixing", name: "泰兴市" }

disguise-headers:
  Referer: "https://onetalk.alibaba.com/"
  Sec-Ch-Ua: '"Chromium";v="128", "Not;A=Brand";v="24", "Microsoft Edge";v="128"'
  Sec-Ch-Ua-Mobile: "?0"
  Sec-Ch-Ua-Platform: '"Windows"'
  User-Agent: "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/128.0.0.0 Safari/537.36 Edg/128.0.0.0"
  Cookie: "ali_apache_id=33.102.195.127.1726301220921.401634.5; cna=JTJsH/uvk2UCAXAEsdIbziUK; t=cbd56c20b81c1fdd2657c81f71fb4f99; xman_us_f=x_l=1; xlly_s=1; _m_h5_tk=3ce5eb1823346cfed6da63befcc835f1_1726640160335; _m_h5_tk_enc=c2252cc739556f62cef3f571ecf9e48d; xman_f=rzJPZe36A5rJIT8lnaCRb2fBfbzWR0NV2D8v+g9QWTxShv+U4fuBSBpj/E8td1lWYCvPx2u7XvAEVGqqQIrcrQKx45G3lVEHGhnLHbeD38NiK99J09VTmw==; ali_apache_track=; ali_apache_tracktmp=; XSRF-TOKEN=a0e7367a-c3b9-488f-b65d-78c44d4efe87; cookie2=184dbbe3527268e7ef89e1d049eea6e0; icbu_s_tag=9_11; isg=BBMTRrdrcdA0_D2L8SaCuA4-opc9yKeK5CqFnMUyTzJ8RDPmTJyr2gVXfrQqZP-C; NWG=NNW; tfstk=fjRrCtNPGbhPeBlQOa5F7QrZr25R1_m6tBsC-eYhPgjuN7ZH3HtDP2H-p6J2xnB5qM6CTw-1D79Se9sU8_dXFWsS268Hf6osffG6yUCRtci_iXN7c6bnOMqdXhMA96mscaKVXQ1pfF95VLYmuw_QraxhEt4c-ib3ZwxhmtbG5ufHx60VnN7UKMf3Zobc5ijht6xHojqWreVV5T06y2la4c7fUGYrBWVeg56PjUj4tcAVzMIMriP3TgeD3T82P0P9l_dwbNtSi7-w-Fph3BrmbMd2oQvHkuuc_EJXCTJqqWSXNi69Z1znZE5P4OAcezPJjE8HCtRjSfCPZgvCweaZVERyVUd2Ry2ca_9VQQ5i6ujBhFRF8BnKgh8HWpX2TuSPAkQcEhOpUk2FEZQVfqu2CL813IR_P-wLptfOuGg5PJedEi7VfqPbpJB86ZSsyL1..; ug_se_c=organic_1726637427015"

captcha-detect:
  landmarks: ["_config_", "captcha", "punish"]

json-parser:
  landmark: "_PAGE_DATA_"
  prefix: "window._PAGE_DATA_ = {"
  suffix: "};"
  offer-list-path: ["offerResultData", "offerList"]
  offer-template:
    detail-url: "action"
    name: "companyName"
    provided-products: "provideProducts"

xpath:
  bill:
    - '//*[@id="8919138051"]/div/div/div/div[3]/div/table/tr[3]/td[2]/div/div/div'
    - '//*[@id="8945312245"]/div/div[2]/div[1]/ul/li[3]/strong'
  address:
    - '//*[@id="8919138051"]/div/div/div/div[3]/div/table/tr[1]/td[4]/div/div/div'
