[tool.poetry]
package-mode = false
name = "alibaba-crawlerplus"
version = "0.2.0"
description = "Crawler project inherited from postgraduate seniors."
authors = ["Cylix Lee <cylix.lee@outlook.com>"]
license = "Apache License 2.0"
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.12"
openpyxl = "^3.1.5"
requests = "^2.32.3"
bs4 = "^0.0.2"
lxml = "^5.3.0"
scrapy = "^2.11.2"
pandas = "^2.2.2"
toml = "^0.10.2"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
